# Generated by Django 4.2.5 on 2024-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('progress', models.CharField(default='T', max_length=50)),
                ('creation_datetime', models.DateField()),
                ('due_datetime', models.DateTimeField()),
                ('created_by', models.TextField()),
                ('assigned_to', models.TextField()),
                ('estimate_time', models.TimeField()),
            ],
        ),
    ]
